export const VsCodeMessageTypes = {
  getSelectedText: 'extension.getSelectedText',
  getChatResponse: 'extension.getChatResponse',
  getPrompts: 'extension.getPrompts',
  getDatasources: 'extension.getDatasources',
  getPromptDetail: 'extension.getPromptDetail',
  getDatasourceDetail: 'extension.getDatasourceDetail',
  getSocketConfig: 'extension.getSocketConfig',
  getModelSettings: 'extension.getModelSettings',
  getApplicationDetail: 'extension.getApplicationDetail',
  getApplications: 'extension.getApplications',
  getDeployments: 'extension.getDeployments',
  copyCodeToEditor: 'extension.copyCodeToEditor',
  stopDatasourceTask: 'extension.stopDatasourceTask',
  stopApplicationTask: 'extension.stopApplicationTask',
}

export const UiMessageTypes = {
  getSelectedText: 'ui.getSelectedText',
  error: 'ui.error',
  startLoading: 'ui.startLoading',
  stopLoading: 'ui.stopLoading',
  getPrompts: 'ui.getPrompts',
  getPromptDetail: 'ui.getPromptDetail',
  getDatasourceDetail: 'ui.getDatasourceDetail',
  getDatasources: 'ui.getDatasources',
  getChatResponse: 'ui.getChatResponse',
  getSocketConfig: 'ui.getSocketConfig',
  getModelSettings: 'ui.getModelSettings',
  getApplicationDetail: 'ui.getApplicationDetail',
  getApplications: 'ui.getApplications',
  getDeployments: 'ui.getDeployments',
  settingsChanged: 'ui.settingsChanged',
  stopDatasourceTask: 'ui.stopDatasourceTask',
  stopApplicationTask: 'ui.stopApplicationTask',
}
