name: Chat Pipeline
on: [pull_request]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.2
          cache: npm
      - run: |
          npm i
          ls
          cd packages/ui
          ls
          npm i
          npm run test